chore: Removes useRefCallback
Doist/ui-extensions pull request #32
Opened 2022-10-26 11:39 UTC by scottlovegrove

This removes the hook `useRefCallback` and replaces it with the equivalent `useEvent` hook.

2022-10-26 11:44 UTC, rfgamaral requested changes

2022-10-26 11:45 UTC, rfgamaral commented
@scottlovegrove I'm having the same issues in `todoist-web` and `twist-web` with the tests breaking, and I'm not yet sure how to fix them... Let me know if you have any ideas!

2022-10-26 11:54 UTC, rfgamaral approved these changes

2023-08-25 08:44 UTC, closed without merging

2023-08-25 08:44 UTC, scottlovegrove commented
Closing this PR for now as it's a bit stale.